### ISSUE TITLE
Faculty Staff page

### ISSUE THREAD

**Issue by masoneli** [phoenixMag00/Kuma#17]
Some suggestions--some of which you are probably already working on: 
1. Exclude the category titles on the profile link (e.g. No "title", "role", etc. on the page with everyone's pictures. Still include them on the profile page)

1.5: Include a category for "website" to also be displayed in the profile link--perhaps under the Phone Number.
1. Add an "all" link to the top when in "Employee Type" view
2. Add the ability to manually order the hierarchy of employee types (not just alphabetical)
3. Maybe make a fixed height equal to the tallest in each row when viewing the profile links? (This would keep columns and rows aligned and avoid the problem of have some rows with two profiles, some with three, most with four, etc.)

**Comment by phoenixMag00** [comment]
1. Are you talking about removing the faculty meta data under the head shots once you click on a specific staff category? Can you shoot me a link to a page? 
2. I def. agree with point 2. That's an awesome idea and probably should of been included in the initial release.
3. If you want to manually order the hierarchy, it's pretty simple. Just modify the Last name field  on the staff custom post page. For example, if you want professor jones to appear before professor adams, then just change the Last Name on Professor Jones field to "A". The last name field is only really there for sorting reasons. I think this should be added to the documentation.
4. I was kinda assuming this was going to happen. Do you happen to have a link to the page with messed up floats? Still thinking of a solution. I was kinda hoping to use jQuery Masonry, but that's not looking like a solution since Masonry puts better layout over correct order. Your idea might work, I will look into it for the next update before the WordPress 3.5 release.

Thanks for your suggestions!

**Comment by masoneli** [comment]
My numbers up there are messed up, so I'll refer to yours. :)

Here's a link to reference issues 1 and 4: http://tuscany.gmu.edu/depts/unilife/eli/faculty-staff/full/

For issue 1, I think it's good to have the metadata clarified on the profile itself, but for the sake of simplicity, I think it would be better to exclude it on the initial page where all the profile links (maybe it's a "directory"?) are. 
1. Cool. I was more referring to the employee types across the top of the page and not the employees themselves, but I think I might be able to do the same with the slugs? This won't be an issue for everyone, but, for instance, full-time faculty might want their directory to be linked ahead of the adjuncts (alas, a comes before f). 
2. Your technobabble makes about 23.7% sense to me. I hope something can be done and that's it's not too much trouble for you to do it. If not, it's not the hugest deal in the world. 

NEW ISSUE: 5. Right now it looks like each employee type is limited to showing 10 profiles. Do I need to change that somewhere? I have 12 profiles in Full-time faculty and more in Adjunct. I can't find a place to increase the limit.

**Comment by phoenixMag00** [comment]
I agree with you. I just made the Faculty and Staff landing page as well as the faculty and staff category pages look uniform. It doesn't show any extra information, because you are right, the user can find that on the employees bio page. It also should keep the look more uniform. I also increased the the number of faculty boxes that can be displayed to infinite. It was set up to pull the global definition, which is 10. That is a bug on my part and has been fixed.

I also noticed you are using an older version of Kuma, please redownload the theme and install it: https://eagle.gmu.edu/download-kuma/kuma.zip
