### ISSUE TITLE
Possibly Add Faculty and Staff Website to meta data

### ISSUE THREAD

**Issue by phoenixMag00** [phoenixMag00/Kuma#18]
I'm up for discussion on this issue. Could be added to next release before WP 3.5

**Comment by masoneli** [comment]
The reason I want this possibility is because many faculty (and some staff) have personal sites for research and CVs, and it would be better to be able to link to those instead of asking them to update their information in two places. 

In the ELI's case, many faculty have class pages--we're working on getting people on blackboard, but some will want to link to class projects that are hosted on other platforms...wikis and moogle. It serves both as a place for students to go as well as a way for the ELI to share teaching philosophy and strategies.

**Comment by phoenixMag00** [comment]
I think adding 1 more field for a website will be fine. Look for it in the next release (1.1.1). Thanks for the suggestion!
