### ISSUE TITLE
Grandchild pages

### ISSUE THREAD

**Issue by masoneli** [phoenixMag00/Kuma#24]
It is possible to have a page that is a child of a child, or does that go against best practices of the web? If not have grandchild pages, is it possible to have more dynamic menus so that upon dropdown, "grandchild" topics don't automatically appear but are instead indicated with an arrow (and then appear on hover)? 

Example is under the F1 Guide on: http://tuscany.gmu.edu/depts/unilife/eli/status/

**Comment by phoenixMag00** [comment]
Ah yes, the grand-child pages. I think this is what I'm going to do for the time being. I really don't like the fly out selection from the drop down menu. I've always have felt that you really only need 1 level of drop downs in the top navigation. That being said, however, there are sites that are going to need that third level.

The current solution I'm going to put into Kuma today: Style the dropdowns with your suggestion. Have an arrow icon to indicate the grandchildren. Also, style the left-side child navigation so that a user knows that the grandchildren are attached to a child and not a parent. 

There will be a patch released today for your site launch tomorrow.
